# Generated by Django 4.0.6 on 2022-10-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0002_book_category_issue_book_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
    ]
