# Generated by Django 4.1.2 on 2022-10-23 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0004_issue_end_date_issue_fine_issue_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='libraryapp.category'),
        ),
    ]
