# Generated by Django 4.0.6 on 2022-10-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0005_issue_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='start_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
