# Generated by Django 4.0.6 on 2022-10-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0006_alter_issue_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
